#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
APP_HOME="`pwd -P`"
MAX_FD="maximum"
warn () { echo "$*"; }
die () { echo; echo "ERROR: $*"; echo; exit 1; }
if [ "$APP_HOME" ] ; then
    case "$APP_HOME" in
        *\ * ) APP_HOME="`echo "$APP_HOME" | sed 's/ /\\ /g'`" ;;
    esac
fi
APP_HOME="`( cd "$APP_HOME" && pwd )`"
if [ -z "$APP_HOME" ] ; then
    die "Unable to determine current directory"
fi
JAVACMD="java"
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found."
fi
CLASSPATH=`dirname "$0"`/gradle/wrapper/gradle-wrapper.jar
if [ -r "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
fi
exec "$JAVACMD" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
